/*
 *  update_api.cpp is part of the HB-RF-ETH firmware v2.0
 *
 *  Original work Copyright 2022 Alexander Reinert
 *  https://github.com/alexreinert/HB-RF-ETH
 *
 *  Modified work Copyright 2025 Xerolux
 *  Modernized fork - Updated to ESP-IDF 6.0 and modern toolchains
 *
 *  The HB-RF-ETH firmware is licensed under a
 *  Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
 *
 *  You should have received a copy of the license along with this
 *  work.  If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

#include <stdio.h>
#include <string.h>

#include "cJSON.h"
#include "esp_app_desc.h"
#include "esp_log.h"
#include "security_headers.h"
#include "update_check.h"
#include "webui.h"
#include "webui_internal.h"
#include "webui_storage.h"

// REST surface of the manual update search. Two endpoints only: ask for a
// check, and read the result. There is no install endpoint at this stage - the
// device reports, it does not act.

static const char *TAG = "WebUI.update";

// Responses are built in one fixed stack buffer. The largest field set is
// bounded by UpdateCheckStatus, so no dynamic JSON assembly is needed.
static constexpr size_t RESPONSE_BUFFER = 768;
static constexpr size_t REQUEST_BUFFER  = 128;

static const char *state_name(update_check_state_t state)
{
    return state == UPDATE_CHECK_RUNNING ? "running" : "idle";
}

// The manifest is generated by us, but it still arrives over the network, so
// its strings are escaped rather than pasted into the response.
static void append_escaped(char *dest, size_t size, const char *value)
{
    size_t out = 0;
    for (size_t i = 0; value[i] != '\0' && out + 2 < size; i++) {
        const unsigned char c = static_cast<unsigned char>(value[i]);
        if (c == '"' || c == '\\') {
            dest[out++] = '\\';
            dest[out++] = static_cast<char>(c);
        } else if (c < 0x20) {
            // Control characters have no place in a version or URL; drop them
            // rather than emitting a \u escape nothing will ever need.
            continue;
        } else {
            dest[out++] = static_cast<char>(c);
        }
    }
    dest[out] = '\0';
}

static esp_err_t send_status(httpd_req_t *req)
{
    const UpdateCheckStatus status = update_check_get_status();

    const esp_app_desc_t *app                    = esp_app_get_description();
    char running_webui[UPDATE_CHECK_VERSION_LEN] = {};
    webui_storage_get_effective_version(running_webui, sizeof(running_webui));

    char latest_fw[UPDATE_CHECK_VERSION_LEN * 2];
    char latest_ui[UPDATE_CHECK_VERSION_LEN * 2];
    char notes[UPDATE_CHECK_URL_LEN * 2];
    char error[UPDATE_CHECK_REASON_LEN * 2];
    char skip[UPDATE_CHECK_REASON_LEN * 2];
    append_escaped(latest_fw, sizeof(latest_fw), status.latestFirmware);
    append_escaped(latest_ui, sizeof(latest_ui), status.latestWebui);
    append_escaped(notes, sizeof(notes), status.notesUrl);
    append_escaped(error, sizeof(error), status.lastError);
    append_escaped(skip, sizeof(skip), status.lastSkipReason);

    char body[RESPONSE_BUFFER];
    const int written = snprintf(
        body, sizeof(body),
        "{\"state\":\"%s\",\"everChecked\":%s,\"channel\":\"%s\","
        "\"lastCheck\":%lld,\"cooldownRemainingSec\":%lu,"
        "\"runningFirmware\":\"%s\",\"runningWebui\":\"%s\","
        "\"latestFirmware\":\"%s\",\"latestWebui\":\"%s\","
        "\"firmwareUpdateAvailable\":%s,\"webuiUpdateAvailable\":%s,"
        "\"notesUrl\":\"%s\",\"lastError\":\"%s\",\"lastSkipReason\":\"%s\"}",
        state_name(status.state), status.everChecked ? "true" : "false", status.channel,
        static_cast<long long>(status.lastCheckUnix),
        static_cast<unsigned long>(status.cooldownRemainingSec), app ? app->version : "",
        running_webui, latest_fw, latest_ui, status.firmwareUpdateAvailable ? "true" : "false",
        status.webuiUpdateAvailable ? "true" : "false", notes, error, skip);

    if (written < 0 || static_cast<size_t>(written) >= sizeof(body)) {
        ESP_LOGE(TAG, "Update status response did not fit its buffer");
        return send_json_error(req, "500 Internal Server Error", "response_too_large");
    }

    httpd_resp_set_type(req, "application/json");
    return httpd_resp_sendstr(req, body);
}

static esp_err_t get_update_status_handler_func(httpd_req_t *req)
{
    add_security_headers(req);
    if (validate_auth(req) != ESP_OK) {
        return httpd_resp_send_err(req, HTTPD_401_UNAUTHORIZED, NULL);
    }
    return send_status(req);
}

static esp_err_t post_update_check_handler_func(httpd_req_t *req)
{
    add_security_headers(req);
    if (validate_auth(req) != ESP_OK) {
        return httpd_resp_send_err(req, HTTPD_401_UNAUTHORIZED, NULL);
    }

    // The channel is the only input, and it is matched against a fixed list
    // rather than interpolated into the URL as received.
    char channel[8] = "stable";
    if (req->content_len > 0) {
        char buffer[REQUEST_BUFFER];
        const int length = recv_full_body(req, buffer, sizeof(buffer));
        if (length < 0) {
            return send_json_error(req, "400 Bad Request", "invalid_body");
        }
        cJSON *root = cJSON_Parse(buffer);
        if (root) {
            const cJSON *item = cJSON_GetObjectItemCaseSensitive(root, "channel");
            if (cJSON_IsString(item) && item->valuestring) {
                if (!update_check_valid_channel(item->valuestring)) {
                    cJSON_Delete(root);
                    return send_json_error(req, "400 Bad Request", "invalid_channel", "channel");
                }
                snprintf(channel, sizeof(channel), "%s", item->valuestring);
            }
            cJSON_Delete(root);
        }
    }

    const update_check_trigger_result_t result = update_check_trigger(channel);
    const char *outcome                        = "accepted";
    const char *status_line                    = NULL;
    switch (result) {
        case UPDATE_CHECK_TRIGGER_ACCEPTED:
            break;
        case UPDATE_CHECK_TRIGGER_BUSY:
            outcome = "busy";
            break;
        case UPDATE_CHECK_TRIGGER_COOLDOWN:
            outcome = "cooldown";
            break;
        case UPDATE_CHECK_TRIGGER_NO_WORKER:
        default:
            outcome     = "unavailable";
            status_line = "503 Service Unavailable";
            break;
    }

    // 202 for accepted work, because the result is not ready yet and the client
    // has to poll /api/update/status for it.
    httpd_resp_set_status(
        req, status_line ? status_line
                         : (result == UPDATE_CHECK_TRIGGER_ACCEPTED ? "202 Accepted" : "200 OK"));
    httpd_resp_set_type(req, "application/json");

    char body[128];
    if (result == UPDATE_CHECK_TRIGGER_COOLDOWN) {
        // The caller cannot derive the remaining window from lastCheck: the
        // cooldown starts at the accepted attempt, including skipped ones, so
        // only the device knows where the window began.
        snprintf(body, sizeof(body),
                 "{\"outcome\":\"cooldown\",\"channel\":\"%s\",\"cooldownRemainingSec\":%lu}",
                 channel,
                 static_cast<unsigned long>(update_check_get_status().cooldownRemainingSec));
    } else {
        snprintf(body, sizeof(body), "{\"outcome\":\"%s\",\"channel\":\"%s\"}", outcome, channel);
    }
    return httpd_resp_sendstr(req, body);
}

httpd_uri_t get_update_status_handler = {.uri      = "/api/update/status",
                                         .method   = HTTP_GET,
                                         .handler  = get_update_status_handler_func,
                                         .user_ctx = NULL};

httpd_uri_t post_update_check_handler = {.uri      = "/api/update/check",
                                         .method   = HTTP_POST,
                                         .handler  = post_update_check_handler_func,
                                         .user_ctx = NULL};
